name: "Xcel iTron MQTT"
description: "Bridge from Xcel iTron smart meters to MQTT"
url: "https://www.github.com/wingrunr21/hassio-xcel-itron-mqtt"
version: "config-breakout"
slug: "xcel-itron-mqtt"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
services:
  - mqtt:need
panel_icon: mdi:meter-electric-outline
map:
  - addon_config:rw
options:
  host:
  username:
  password:
  port:
  meter_ip:
  meter_port: 8081
  cert_dir: /config/certs
  cert_file: cert.pem
  key_file: key.pem
schema:
  host: str
  username: str
  password: str
  port: port?
  meter_ip: str
  meter_port: port
  ldfi: str?
  cert_dir: str?
  cert_file: str?
  key_file: str?
